# Generated by Django 5.0 on 2024-01-03 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ru', [('Видео', 'Видео'), ('Фото', 'Фото')]), ('en', [('Видео', 'Video'), ('Фото', 'Photo')]), ('uz', [('Видео', 'Video'), ('Фото', 'Foto')])], max_length=5)),
                ('src', models.FileField(upload_to='src/')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('subscriptions', models.ManyToManyField(through='main.Subscription', to='main.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ru', [('Видео', 'Видео'), ('Фото', 'Фото')]), ('en', [('Видео', 'Video'), ('Фото', 'Photo')]), ('uz', [('Видео', 'Video'), ('Фото', 'Foto')])], max_length=5)),
                ('src', models.FileField(upload_to='src/')),
                ('title', models.TextField()),
                ('title_en', models.TextField(blank=True)),
                ('title_ru', models.TextField(blank=True)),
                ('title_uz', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ru', [('Видео', 'Видео'), ('Фото', 'Фото')]), ('en', [('Видео', 'Video'), ('Фото', 'Photo')]), ('uz', [('Видео', 'Video'), ('Фото', 'Foto')])], max_length=5)),
                ('src', models.FileField(upload_to='src/')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.posts')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.stories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.userprofile')),
            ],
        ),
    ]
